version: 0.2

phases:
  install:
    runtime-versions:
        java: corretto8
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/convert-units-jolson490-0.0.1-SNAPSHOT.war convert-units-jolson490-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - convert-units-jolson490-0.0.1-SNAPSHOT.war
  base-directory: 'target/convert-units-jolson490-0.0.1-SNAPSHOT'
