version: 0.2

phases:
  install:
    runtime-versions:
        java: corretto11
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'target/convert-units-jolson490-0.0.1-SNAPSHOT.jar'
