version: 0.2

phases:
  install:
    runtime-versions:
        java: corretto8
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/sampleapp-jolson490-0.0.1-SNAPSHOT.war sampleapp-jolson490-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - '**/*'
  base-directory: 'target/sampleapp-jolson490-0.0.1-SNAPSHOT'
